version: "3.4"

services:
  web:
    image: export-excel:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    hostname: export.tirtasatria.tech
    networks:
      - back-tier
    entrypoint:
      - node
      - server.js

networks:
  back-tier:
    external: true

